name: Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Or the default branch you want to use

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme
          pip install pandas
          pip install numpy
          pip install matplotlib
          pip install scipy
          pip install scikit-learn
          pip install seaborn
          

      - name: Build Sphinx documentation
        run: |
          cd docs  # Adjust this if your Sphinx files are in a different folder
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
